#define IDF 1
#define OP 2
#define BEGIN 3
#define END 4
#define VARINT 5
#define VARFLOAT 6
#define VARBOOL 7
#define INT 8
#define FLOAT 9
#define BOOL 10
#define IF 11
#define FOR 12
#define DEBUT 13
#define FIN 14
#define AFFECTATION 15
#define SEMICOLON 16
#define ARC 17
#define FARC 18
#define VG 19
#define PVG 20
#define PLUS 21
#define MINUS 22
#define PAROPEN 23
#define PARCLOSE 24
#define CURLOPEN 25
#define CURLCLOSE 26
